Delete arvosanas first and suoritus after
Deleting arvosana after suoritus causes and error in Sure:

2016-11-17T14:27:11.674+02 INFO  {} [qtp597190999-16] INFO  fi.vm.sade.auditlog.Audit: {"timestamp":"2016-11-17T14:27:11.674+02","serviceName":"hakurekisteri","applicationType":"virkailija","
resourceId":"9e7565f1-f8f5-466a-a797-08818a2f37c9","resourceName":"Arvosana","id":"1.2.246.562.24.23516840553","operaatio":"RESOURCE_DELETE"}
2016-11-17T14:27:11.809+02 ERROR {} [hakurekisteri-akka.actor.default-dispatcher-19441] ERROR fi.vm.sade.hakurekisteri.web.arvosana.ArvosanaResource: incident d3d177f0-d64b-4779-8ed7-f096c479136d
java.util.NoSuchElementException: key not found: 2230e293-c5ee-4b0f-9ff4-17a1bfcbb177
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at support.AuthorizedRegisters$$anonfun$10$$anonfun$apply$9$$anonfun$apply$10.apply(Registers.scala:85)
...